
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use the constants directly rather than environment variables
const SUPABASE_URL = "https://bhirorpogkfnafuxfkox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoaXJvcnBvZ2tmbmFmdXhma294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODA2NDMsImV4cCI6MjA2MjU1NjY0M30.0c2AKpiQQuyCU7-QkvpXpu1rm1Ex06x4gAiH3BX9l4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
